### ISSUE TITLE
Aufgabeneinteilung

### ISSUE THREAD

**Issue by LaraM2003** [LaraM2003/WissenschaftlichesArbeiten2023_24#1]
Wer möchte welche Teilaufgabe machen?

**Comment by AlainKauth** [comment]
Hi zusammen, ich würde gerne Aufgabe 1 übernehmen, wenn das in Ordnung ist 😃

**Comment by HenryDoebbel** [comment]
Hi ich würde auch gerne Aufgabe 1 machen, falls keiner da was gegen hat. Würde dann sagen das ich einfach den ersten Teil mache und du den zweiten okay?

**Comment by FatimaNachati** [comment]
👍
