### ISSUE TITLE
Aufgabe 5 - Besprechung der Ergebnisse

### ISSUE THREAD

**Issue by LaraM2003** [LaraM2003/WissenschaftlichesArbeiten2023_24#5]
Hallo Zusammen,

Aufgabe 5 des Aufgabenblatts ist ja die Besprechung der Ergebnisse aus Aufgabe 4. Die sind zwar noch nicht ganz vollständig, aber der Großteil ist schon vorhanden. Gebt also gerne Anmerkungen (und vielleicht auch Vorschläge, was man noch ergänzen könnte) unter diesem Issue ab. Fatima und ich werden dann versuchen diese zeitnah einzuarbeiten.

**Comment by AlainKauth** [comment]
Hi zusammen, 

hier mein erstes Feedback zur Aufgabe 5.

1.) Ganz im Sinne von **Korrelation vs. Kausalität würde ich die Formulierungen "abschwächen"** und z.B. von _möglichen_ Einflussfaktoren sprechen. Unsere bisherige Analyse ist (und soll m. E. auch) nur deskriptiv sein. Für eine kausale Inferenz müsste man darüberhinaus gehen. 

2.) Bezüglich der beachteten bzw. analysierten Variablen haben wir die Hauptinteraktionen beachtet. Ggfls. könnte man noch für ein besseres "Hintergrund"-Verständnis **andere Merkmale gegeneinander plotten bzw. analysieren**. So sind bestimmt Alter und Fare miteinander korreliert (Je Älter eine Person, desto wohlhabender war er) etc.. Da müsste ich auch noch einmal genauer reinsehen. Vlt. hat @HenryDoebbel Ideen?

3.) Ich würde evtl. noch mal **schönere und "handfeste" Grafiken** erstellen. Also mit Titel, Beschriftung etc. und diese als Ergebnisse exportieren (damit sind die Abbildungen leichter verständlich bzw. sogar selbsterklärend und man muss nicht immer den Code laufen lassen um sich die grafischen Ergebnisse ansehen zu wollen).

**Comment by HenryDoebbel** [comment]
Hey,

ich finde die Ergebnisse der Analyse schon echt aufschlussreich und hätte jetzt nicht mehr wirklich viel dem hinzuzufügen.
Man könnte sich noch vielleicht durch einen Zusammenhang von der Kabinenseite der überlebenden und gestorbenen Passagiere überlegen, auf welcher Seite der Eisberg beim Crash war, aber sonst würde mir erstmal nichts einfallen.
Die Idee mit den Grafiken von Alain finde ich aber auch gut, um das Ganze noch übersichtlicher zu gestalten.

**Comment by LaraM2003** [comment]
Ich habe jetzt versucht, so viele eurer Anmerkungen wie möglich umzusetzen. Schaut gerne nochmal kurz rein und sagt mir, ob das so ist, wie ihr es euch vorgestellt habt.

**Comment by HenryDoebbel** [comment]
Sieht sehr gut aus! Finde die neuen Plots haben das ganze nochmal gut abgerundet. Ich hätte dann auch keine neuen Vorschläge mehr und würde sagen man kann abgeben.

**Comment by FatimaNachati** [comment]
Ich habe jetzt nochmal überall drüber geschaut und bin auch zufrieden mit den Ergebnissen :) Vorschläge gäbs von meiner Seite dann auch nicht mehr.

**Comment by AlainKauth** [comment]
Ich habe die letzten kleinen Änderungen vorgenommen (Dokumentation ergänzt, Umlaute umgeschrieben, sprechende Funktionsnamen verteilt). Bitte noch einmal ein letztes Mal prüfen, ob der Code so lauffähig ist, da ich einige Funktionsnamen geändert habe. (Bei mir klappt alles wunderbar, aber doppelt kontrolliert ist dann doch besser).

**Comment by LaraM2003** [comment]
Habe es gerade ausprobiert und es läuft problemlos durch
